# -*- rpm-spec -*-
BuildRoot:      /home/mvitolin/projects/endurox/_CPack_Packages/Linux/RPM/endurox-2.4.3-1.linuxmint17_2.x86_64
Summary:        Enduro/X Middleware Platform
Name:           endurox
Version:        2.4.3
Release:        1
License:        unknown
Group:          unknown
Vendor:         Humanity













Prefix: /usr


%define _rpmdir /home/mvitolin/projects/endurox/_CPack_Packages/Linux/RPM
%define _rpmfilename endurox-2.4.3-1.linuxmint17_2.x86_64.rpm
%define _unpackaged_files_terminate_build 0
%define _topdir /home/mvitolin/projects/endurox/_CPack_Packages/Linux/RPM




%description
DESCRIPTION
===========

This is an installer created using CPack (http://www.cmake.org). No additional installation instructions provided.



# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT "/home/mvitolin/projects/endurox/_CPack_Packages/Linux/RPM/tmpBBroot"

#p build

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv "/home/mvitolin/projects/endurox/_CPack_Packages/Linux/RPM/tmpBBroot" $RPM_BUILD_ROOT

%clean

%post


%postun


%pre


%preun


%files
%defattr(-,root,root,-)
%dir "/usr/share/endurox"
%dir "/usr/share/endurox/config"
"/usr/share/endurox/config/ndrxconfig.xml"
"/usr/share/endurox/config/debug.conf"
"/usr/share/endurox/config/ndrx_home"
"/usr/share/endurox/config/init-d-rhel-endurox-user"
"/usr/share/endurox/config/setndrx"
"/usr/share/endurox/config/endurox-sys-env.sh"
%dir "/usr/share/endurox/doc"
%dir "/usr/share/endurox/doc/html"
"/usr/share/endurox/doc/html/getting_started_tutorial.html"
"/usr/share/endurox/doc/html/building_guide.html"
"/usr/share/endurox/doc/html/ex_adminman.html"
"/usr/share/endurox/doc/html/ex_overview.html"
"/usr/share/endurox/doc/html/ex_devguide.html"
%dir "/usr/share/endurox/doc/pdf"
"/usr/share/endurox/doc/pdf/xadmin.pdf"
"/usr/share/endurox/doc/pdf/ex_devguide.pdf"
"/usr/share/endurox/doc/pdf/ex_overview.pdf"
"/usr/share/endurox/doc/pdf/ndrxconfig.xml.pdf"
"/usr/share/endurox/doc/pdf/tpbridge.pdf"
"/usr/share/endurox/doc/pdf/tpevsrv.pdf"
"/usr/share/endurox/doc/pdf/ud.pdf"
"/usr/share/endurox/doc/pdf/ex_env.pdf"
"/usr/share/endurox/doc/pdf/getting_started_tutorial.pdf"
"/usr/share/endurox/doc/pdf/ndrxdebug.conf.pdf"
"/usr/share/endurox/doc/pdf/ndrxd.pdf"
"/usr/share/endurox/doc/pdf/tprecover.pdf"
"/usr/share/endurox/doc/pdf/mkfldhdr.pdf"
"/usr/share/endurox/doc/pdf/tmsrv.pdf"
"/usr/share/endurox/doc/pdf/cpmsrv.pdf"
"/usr/share/endurox/doc/pdf/building_guide.pdf"
"/usr/share/endurox/doc/pdf/ex_adminman.pdf"
"/usr/share/endurox/doc/pdf/ex_envover.pdf"
%dir "/usr/share/endurox/ubftab"
"/usr/share/endurox/ubftab/Exfields"
%dir "/usr/share/man"
"/usr/share/man/man5*"
"/usr/share/man/man5/ndrxdebug.conf.5*"
"/usr/share/man/man5/ex_env.5*"
"/usr/share/man/man5/ex_envover.5*"
"/usr/share/man/man5/ndrxconfig.xml.5*"
"/usr/share/man/man8*"
"/usr/share/man/man8/tpbridge.8*"
"/usr/share/man/man8/tmsrv.8*"
"/usr/share/man/man8/tprecover.8*"
"/usr/share/man/man8/xadmin.8*"
"/usr/share/man/man8/ndrxd.8*"
"/usr/share/man/man8/mkfldhdr.8*"
"/usr/share/man/man8/cpmsrv.8*"
"/usr/share/man/man8/tpevsrv.8*"
"/usr/share/man/man8/ud.8*"
"/usr/include/ubf.h"
"/usr/include/atmi.h"
"/usr/include/userlog.h"
"/usr/include/exparson.h"
"/usr/include/fml32.h"
"/usr/include/xatmi.h"
"/usr/include/fml.h"
"/usr/include/pscript.h"
"/usr/lib/libnstd.so"
"/usr/lib/libps.so"
"/usr/lib/libubf.so"
"/usr/lib/libpsstdlib.so"
"/usr/lib/libatmiclt.so"
"/usr/lib/libexnet.so"
"/usr/lib/libnetproto.so"
"/usr/lib/libndrxxaorad.so"
"/usr/lib/libatmisrvinteg.so"
"/usr/lib/libatmisrvnomain.so"
"/usr/lib/libatmisrv.so"
"/usr/lib/libndrxxaoras.so"
"/usr/lib/libatmi.so"
"/usr/bin/tprecover"
"/usr/bin/tmsrv"
"/usr/bin/tpevsrv"
"/usr/bin/ckserver.sh"
"/usr/bin/pscript"
"/usr/bin/tmshutdown"
"/usr/bin/mkfldhdr"
"/usr/bin/cpmsrv"
"/usr/bin/tmboot"
"/usr/bin/tpbridge"
"/usr/bin/fdown.sh"
"/usr/bin/xadmin"
"/usr/bin/ndrxd"
"/usr/bin/buildclient"
"/usr/bin/ud"
"/usr/bin/buildserver"
"/usr/bin/tmadmin"
"/usr/bin/ndrxd_chkdown.sh"




%changelog
* Sun Jul 4 2010 Eric Noulard <eric.noulard@gmail.com> - 2.4.3-1
  Generated by CPack RPM (no Changelog file were provided)
